### ISSUE TITLE
Mentions from MC to Discord

### ISSUE THREAD

**Issue by Mohron** [shadowfacts/DiscordChat#13] opened 2016-01-31 01:11 UTC
When you type @DiscordUN on Minecraft it doesn't actually turn to a mention on discord. is this possible to add as a feature?

**Comment by Gunner76th** [comment] 2016-05-29 02:06
just an FYI, this is a duplicate of https://github.com/shadowfacts/DiscordChat/issues/31

**Comment by shadowfacts** [comment] 2016-11-26 17:27
Added in the rewrite, which will be released soon.

**Closed as completed** 2016-11-26 17:26 UTC
Labels: enhancement
