### ISSUE TITLE
Feature Request: Highlighting in Discord through MC

### ISSUE THREAD

**Issue by CandiceJoy** [shadowfacts/DiscordChat#31] opened 2016-05-03 17:33 UTC
Would it be possible to allow for highlighting of Discord client through MC?  Currently it doesn't work, even when using the number after the name.

https://goo.gl/AAOwpy

**Comment by shadowfacts** [comment] 2016-05-03 21:53
I tried to do this a while ago however the problem is that people's names can literally be anything (including whitespace and all sorts of special characters) making it impossible to my knowledge to make write a regex that properly matches everything.

This should be possible with the @name#number thing, I'll take a look at it Soon™.

Unrelated side note: Tlove-senpai & co. are using my things 😄

**Comment by CandiceJoy** [comment] 2016-05-04 03:24
Haha yeah, I'm the admin in charge of all the Minecraft stuff for tlove.  I was waiting on someone else to do some minor updates to the newest version of the pack and someone recommended your mod.  I took one look at it and I was like "oh heck yes!".  We used to run eirairc back when we were using IRC and, frankly, I didn't figure anything existed for Discord in 1.8.9 yet.  At any rate, the server isn't even open yet except for testing and your mod has already been a huge hit with pretty much everyone :D  I'm really impressed that formatting works, as well ^_^

I know my friend Chikachi got mentions working in a matter of like 30 mins, so if you'd like a shortcut to figuring it out yourself, you can talk to her (@TheChikachi on Twitter).  She said this is how she did it: "Just look through all users on the discord server and check for the name and then replace it with the format Discord wants".  I have noticed that mentioning @Name#Number manually doesn't work, though, and I'm not overly familiar with Discord's backend, so :P

**Comment by Gunner76th** [comment] 2016-05-29 02:05
I know it is for Discord.js, but would this be of any use in being able to implement this feature? https://github.com/hydrabolt/discord.js/issues/46

**Comment by shadowfacts** [comment] 2016-11-26 17:27
Added in the rewrite, which will be released soon.

**Closed as completed** 2016-11-26 17:27 UTC
Labels: enhancement
