### ISSUE TITLE
When discord is down

### ISSUE THREAD

**Issue by ThomasAunvik** [shadowfacts/DiscordChat#82] opened 2017-03-20 20:08 UTC
Brief explanation of issue:

When the Discord Servers are down, the server wants to connect to the discord channel, but it fails.
What my conclusion is that every time the discord chat fails to connect it tries to connect again. Making an infinite loop of connecting.

I would wish there was a max amount of tries till it continues without DiscordChat.

Steps to reproduce:
- Make discord servers crash/fail
- Launch server

Link to crash report/log in a [gist](https://gist.github.com/ThomasAunvik/770e11911be69090e1a9f53bd9bd6378):

DiscordChat version:
2.0.4

Minecraft version:
1.11.2

**Comment by canilsen** [comment] 2017-03-20 20:10
Can confirm. It crashed the server while Discord is having issues, Restarting server doesn't help.
Edit: This is on 1.10

**Comment by ThomasAunvik** [comment] 2017-03-20 20:13
What my solution was to remove the discord mod.

**Comment by canilsen** [comment] 2017-03-20 20:20
Yeah I'm doing the same until Discord connection is stable again

**Comment by cha0s** [comment] 2017-03-20 20:41
Already reported in #81 but yeah, this is a big problem ;)

**Comment by shadowfacts** [comment] 2017-03-20 20:44
Duplicate of #81

**Closed as completed by shadowfacts** 2017-03-20 20:44 UTC
