### ISSUE TITLE
Server hangs on startup message

### ISSUE THREAD

**Issue by Watchful1** [shadowfacts/DiscordChat#80] opened 2017-03-19 20:26 UTC
Just today after a scheduled restart my server started hanging when discordchat tried to send the server started message. There's no crash, but here's the section from the log.

http://pastebin.com/fAhrJwJZ

DiscordChat version: 2.0.4

Minecraft version: 1.10.2

**Comment by Watchful1** [comment] 2017-03-19 20:34
So I found the problem, in my config file the line `channel="minecraft"` changed to `channel=minecraft` without me doing anything. I changed it back and it's working now.

**Comment by Watchful1** [comment] 2017-03-20 20:32
The server did exactly the same thing at exactly the same time today. I searched through several tens of thousands of lines of logs, but there was no indications anything happened.

**Comment by shadowfacts** [comment] 2017-03-20 20:40
Huh, that's weird. I'll try to see if I can reproduce it.

**Comment by Watchful1** [comment] 2017-03-20 22:20
The config thing was a red herring. The one without quotes works fine. I must have just had an old version stored and hadn't noticed it converting.

I don't know what happened yesterday, but discord was having a major outage about the time it happened today. It would be nice if it just printed a warning or crashed in that case, but it's probably not your fault.

**Comment by cha0s** [comment] 2017-03-21 00:45
Yeah, it's probably the same as #81 I just didn't connect the two because when I read your issue earlier today you had responded about the quote thing. So technically mine is a duplicate of this :) I'll leave it open though because of the more specific crash log and stuff.

**Closed as completed** 2017-06-20 15:44 UTC
Labels: bug
