### ISSUE TITLE
Server Output

### ISSUE THREAD

**Issue by Towsty** [shadowfacts/DiscordChat#4] opened 2016-01-22 00:05 UTC
Seems that any text sent from the server itself has issues sending anything after a space.

![image](https://cloud.githubusercontent.com/assets/5897643/12498614/754e1994-c069-11e5-932e-0d4c71021f11.png)

In that image, after **SERVER there should be text with the remaining time until reboot. If you /say from the console, anything after a space has the same result.

**Comment by shadowfacts** [comment] 2016-01-22 00:50
I can't reproduce this, using /say either from the server console or ingame. What mod (or plugin, or whatever) is sending these messages?

**Comment by Towsty** [comment] 2016-01-22 01:26
In this particular instance it was YABM2
Even just /say commands did it for me though:

![image](https://cloud.githubusercontent.com/assets/5897643/12500002/d2ddb8f2-c074-11e5-8bbd-e281fced7d3d.png)

![image](https://cloud.githubusercontent.com/assets/5897643/12500014/e0dbea14-c074-11e5-8af5-bc0f37cf0124.png)

![image](https://cloud.githubusercontent.com/assets/5897643/12500008/da740a3a-c074-11e5-9e31-67ecb38f6e11.png)

I'll post some logs and mod lists in a few

**Comment by shadowfacts** [comment] 2016-11-26 17:33
Closing this as I still have no idea how this is even possible. /say still doesn't send Discord messaegs

**Closed as completed by shadowfacts** 2016-11-26 17:33 UTC
Labels: bug
